name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 'Setup Node.js 18 LTS'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run Check
        run: npm run check
      - name: Run lint
        run: npm run lint
      - name: Run Build
        run: npm run build
      - name: Run Build GH-Page
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          npm run build:gh-pages
          touch build/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
